services:
  thumbor:
    image: ghcr.io/altendorfme/thumbor:latest
    container_name: thumbor
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8888:8888"
    environment:
      - DOMAIN=site.xyz
      - THUMBOR_NUM_PROCESSES=4
      - SECURITY_KEY= # https://jwtsecretkeygenerator.com/
      - ALLOW_UNSAFE_URL= True
    volumes:
      # Data directories
      - thumbor_data:/data
      - thumbor_logs:/var/log/supervisor
      - thumbor_nginx_cache:/var/cache/nginx/thumbor
      
      # SSL certificates (Let's Encrypt)
      - letsencrypt_certs:/etc/letsencrypt
      - ssl_certs:/etc/ssl/certs
      - certbot_webroot:/var/www/certbot

    networks:
      - thumbor

    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  thumbor:
    driver: bridge

volumes:
  thumbor_data:
    driver: local
  thumbor_logs:
    driver: local
  thumbor_nginx_cache:
    driver: local
  letsencrypt_certs:
    driver: local
  ssl_certs:
    driver: local
  certbot_webroot:
    driver: local